### ISSUE TITLE
Host address ovveriding

### ISSUE THREAD

**Issue by santoshreddy17** [kumuluz/kumuluzee-swagger#5]
@jmezna 
Is there a way of overriding the host address on swagger definition when we deploy the application on something like openshift ?

@SwaggerDefinition(info = @Info(title = "KumuluzEE Archetype API", version = "v1.0.0"), host = "localhost:8080")

**Comment by santoshreddy17** [comment]
If we remove host parameter from swagger definition
It adds extra http:// in front of the url: 
This is causing the issue :

![image](https://user-images.githubusercontent.com/40468999/43899863-258390ce-9bdb-11e8-80ea-6bd1fe31b85b.png)

**Comment by zvonegit** [comment]
> Is there a way of overriding the host address on swagger definition when we deploy the application on something like openshift?

Not at the moment, expect support for this in next version. We intend to add a configuration property that will allow you to change the host address. 

> If we remove host parameter from swagger definition
> It adds extra http:// in front of the url

We will look into it.

**Comment by zvonegit** [comment]
Fixed in v1.2.0
